### ISSUE TITLE
Request to be added to the PSN

### ISSUE THREAD

**Issue by leogaggl** [OrderOfTheBee/marketing#21]
# Brightcookie Pty Ltd

[Website](http://www.brightcookie.com/)
## About us

We are an Adelaide South Australia based Online Learning Specialist company supporting clients in anything related to the delivery of Online Learning. Our clients are typically Educational & Training Providers in the Schools, VET (Adult Education) and Higher Education Sector as well as corporate training departments.

We have used Alfresco Community Edition for over 5 years now to support some of our larger clients with Alfresco CE as a Learning Object Repository with associated workflows to produce these Learning Materials. We have also connected Alfresco to a number of Learning Management Systems (such as Moodle LMS) as well as Social Learning Platforms.
## Clients

Some of our clients which use Alfresco include
- [Tabor College](http://taboradelaide.edu.au/) - would be willing to be a case study
- [TAFE SA](http://tafesa.edu.au/)
- [TAFE NSW](https://www.tafensw.edu.au/)
- [Adelaide to Outback General Practitioner Training](http://adelaidetooutback.com.au/)
- [Northern Territory General Practitioner Education](http://ntgpe.org/)
- SA Health Department
## Staff

We currently have 3 staff members working with Alfresco CE
Leo Gaggl - [LinkedIn](https://au.linkedin.com/in/leogaggl)
Kien Vu - [LinkedIn](http://au.linkedin.com/in/kienvu)
Marcus Fabriczy - [LinkedIn](https://www.linkedin.com/profile/view?id=AAkAABKfdJ8B8ps0XKO-UmthWzwwTyEDzNBAnSI)
## Technical

Our supported Operating Systems are CentOS and Ubuntu (with all new installations defaulting to Ubuntu of late). Currently we don't have any open repositories, but would be happy to start contributing some in future as well as assisting with blog entries and case studies in educational environments. Additionally we would be happy to contribute pieces of documentation on how to connect Alfresco to Educational Systems.

**Comment by aviriel** [comment]
Hello Leo,

Nice to receive your request. I would be happy to publish Brightcookie Pty Ltd to Professional Services Network, but I have to ask you to provide some additional information.

We should publish something that will confirm your competence. I didn't find anything that is open sourced on your website. Also your blog does not contain any technical posts about Alfresco. You provided in your request names of your customers, but there are no success stories about your implementation of Alfresco Community published on your website or on the OOTB website. Can you provide fix for one or more points?

Best regards,
Oksana

**Comment by leogaggl** [comment]
Hi Oksana,

There is currently 2 Alfresco related blog entries on our website:

http://www.brightcookie.com/2015/09/updated-alfresco-and-moodle-integration/ (CMIS)
http://www.brightcookie.com/2012/01/alfresco-plug-in-for-moodle-2/ (older version of Moodle Integration).

Our solutions page has a section on Alfresco too: http://www.brightcookie.com/what-we-do/solutions/

We will publish 2 more Alfresco related blogs (integration with [Mahara](https://mahara.org/) and [Totara Social](https://www.totaralms.com/solutions/totara-social) in the next 2 weeks.

We are planning further ones showing the use of Alfesco workflows in an educational context. I will let you know as soon as published and if you want we would be happy if you want to use the on the OOTB site. We are also working on the case study for Tabor mentioned in the OP.

Best regards,
Leo

**Comment by leogaggl** [comment]
Hi Oksana,

Do you require further info ?

Cheers,
Leo

**Comment by aviriel** [comment]
Hi Leo,

Thank you, I added this information to the website (https://github.com/OrderOfTheBee/OrderOfTheBee.github.io/commit/8243889eafb5924d47e4c52e6811eaf8a717dce9). The information you provided is not exactly what I mean, but I believe you will improve it later. :)

**Regarding blog posts:**

You tell about benefits of your solutions, show that they really work. It's great, but a few new posts about doing something with Alfresco with code snippets or similar, are welcome. Maybe about things that your engineers learnt while they developed the integration plugin. 

Samples from other PSN members: http://douglascrp.blogspot.ru/2015/05/how-to-remote-debug-with-alfresco-sdk-21.html, http://alfresco-ecm.cz/wp/2015/03/22/alfresco-5-libreoffice-working/, https://www.loftux.com/en/blog/select-metadata-edit-form-based-on-aspect#sthash.Vt0nmBBA.dpbs and http://www.keensoft.es/en/development-in-alfresco-how-to-run-processes-with-administrator-privileges/.

Showing the use of Alfesco workflows in an educational context can become a very good post.

**Regarding repositories / addons**

> Our solutions page has a section on Alfresco too: http://www.brightcookie.com/what-we-do/solutions/

It confirms that you offer Alfresco-related services, but it does not confirm your competence, because user cannot download anything from this page, even see the source code of the product. Usually customers do not look at source code or can understand is it bad or good, but they should have a chance to do it. And we as an Order of the Bee can confirm that you know what you do if we can look at the source code of your add-ons on Github, for example.

**Customers**

Tell me, if you publish any success stories about your Alfresco-related services on the website, I'll add a link from the OOTB website.

P.S. looks like I'm very angry. Sorry for this, it's not true. :) We just try to be very careful with checking the competence of the Professional Services Network members.
